#-------------------------------
# General Site Settings
title: My Portfolio
email: alsushkevich@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

skills:
- {name: Communication, value: '8'}
- {name: HTML/CSS, value: '8'}
- {name: Organization, value: '9'}
- {name: Python/Django, value: '7'}
- {name: Planning, value: '7'}
- {name: JavaScript/jQuery, value: '5'}
- {name: Learning, value: '10'}
- {name: Ruby/PHP, value: '4'}

# Work Section

projects:
- {name: Project1, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}
#-------------------------------
# Clients Section

clients:
- {avatar: '1.jpg',
  name: 'Robby Spencer',
  # title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Aliaksandr was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer.</p>',
  logo: 'logo1.png'}
- {avatar: '2.jpg',
  name: 'Veronica Sabina',
  # title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>Work with Alex was a pleasure.</strong> He understood exactly what I wanted and created an awesome site for me.</p>',
  logo: 'logo2.png'}
- {avatar: '3.jpg',
  name: 'Oscar  Daniels',
  # title: 'Social Media Girl, Quebec Int.',
  quote: '<p><strong>Awesome to work with.</strong> Incredibly organized, easy to communicate with, responsive with next iterations, and beautiful work.</p>',
  logo: 'logo3.png'}
- {avatar: '4.jpg',
  name: 'Anna Melnik',
  # title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>I am really happy with the results. </strong>Get 100% satisfaction is difficult but Alex got it without problems.</p>',
  logo: 'logo4.png'}


