#-------------------------------
# General Site Settings
title: My Portfolio
email: alsushkevich@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Pet Projects, url: '#projects'}
- {name: Feedback, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

# seo:
#   description: 'Provide a description for your website to make it visible to search engines.'
#   rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
#   rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

skills:
- {name: Communication, value: '9'}
- {name: Programming, value: '9'}
- {name: Organization, value: '9'}
- {name: UI/UX skills, value: '8'}
- {name: Planning, value: '7'}
- {name: Website Optimization, value: '7'}
- {name: Learning, value: '10'}
- {name: DevOps skills, value: '7'}


# Work Section
work:
- {name: Dynamo, folder: 'dynamo'}
- {name: Kwickdoctor, folder: 'kwickdoctor'}


# Pet Projects Section
project-categories:
- {name: "All", class: "show-all"}
- {name: "HTML mockups", class: "show-html"}
- {name: "JavaScript", class: "show-javascript"}
- {name: "AngularJS", class: "show-angular"}

projects:
- {name: Frogger game, class: "javascript-project", folder: 'proj-9'}
- {name: RiceRocks, class: "html-project", folder: 'proj-2'}
- {name: AFG landing page, class: "html-project", folder: 'proj-11'}
- {name: Barbershop, class: "html-project", folder: 'proj-12'}
- {name: Newsroom, class: "html-project", folder: 'proj-1'}
- {name: Agency website, class: "html-project", folder: 'proj-4'}
- {name: Move, class: "html-project", folder: 'proj-3'}
# - {name: Excursion, class: "html-project", folder: 'proj-5'}
- {name: Bass, class: "html-project", folder: 'proj-6'}
- {name: Angular Blog, class: "angular-project", folder: 'proj-13'}
# - {name: To-do app, class: "javascript-project", folder: 'proj-7'}
- {name: Bolt network, class: "html-project", folder: 'proj-8'}
- {name: Video spa, class: "javascript-project", folder: 'proj-10'}
- {name: Angular Calculator, class: "angular-project", folder: 'proj-14'}


# Clients Section
clients:
- {
  avatar: 'jelena-m.jpg',
  name: 'Jelena Milosevic',
  title: 'Project Manager, Dynamo',
  quote: '<p><strong>Awesome to work with.</strong> Incredibly organized, easy to communicate with, responsive with next iterations, and beautiful work.</p>',
  # logo: 'logo3.png'
}
- {
  avatar: '1.jpg',
  name: 'Robby Spencer',
  # title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Aliaksandr was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer.</p>',
  # logo: 'logo1.png'
}
- {
  avatar: '2.jpg',
  name: 'Veronica Sabina',
  # title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>Work with Alex was a pleasure.</strong> He understood exactly what I wanted and created an awesome site for me.</p>',
  # logo: 'logo2.png'
}
- {
  avatar: '3.jpg',
  name: 'Oscar  Daniels',
  # title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>I am really happy with the results. </strong>Get 100% satisfaction is difficult but Alex got it without problems.</p>',
  # logo: 'logo4.png'
}


# Social Section
social:
  - { icon: 'so.svg', link: 'https://stackoverflow.com/users/7600492/aliaksandr-sushkevich' }
  - { icon: 'github.svg', link: 'https://github.com/aliaksandr-s' }
  - { icon: 'codepen.svg', link: 'https://codepen.io/alscream/' }